<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNy8jjXQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNy8jjXQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNy8jjXQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNy8jjXQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNy8jjXQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ny8jjXQ',
    'container.build_id' => '8bca2cbf',
    'container.build_time' => 1743493305,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNy8jjXQ');
